name: Update Supporters List

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Fetch supporters and update README
        run: node .github/scripts/update-patrons.js

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PR_TITLE: "Update supporters list"
          PR_BODY: "This PR updates the supporters list"
          BRANCH_NAME: "update/patrons"
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout -b ${BRANCH_NAME}
          git add README.md
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "docs: updated patrons list"
            git push origin HEAD
            gh pr create --title "$PR_TITLE" --body "${PR_BODY}"
            gh pr merge --auto --delete-branch --squash "$BRANCH_NAME"
          fi
          
